In [ ]:
import numpy as np
import sys


In [37]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],dtype='int8')
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
a[0,1:-1:2]

array([2, 4, 6], dtype=int8)

In [53]:
# Initialize zeros array
np.zeros((2,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
# Initialize ones array
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
# Any other number
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [57]:
# Random Decimal Numbers
np.random.rand(2,3,2)

array([[[0.42746818, 0.39324843],
        [0.71090136, 0.23082931],
        [0.03350664, 0.4084974 ]],

       [[0.95112581, 0.06120297],
        [0.88748133, 0.07618627],
        [0.45228968, 0.45680141]]])

In [62]:
# Random integer values
np.random.randint(4,90,size=(4,3))

array([[82, 78, 30],
       [84, 38, 74],
       [50, 40, 78],
       [18, 46, 76]])

In [63]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a.itemsize
a.shape
a.nbytes

14

In [74]:
a = np.ones((5,5))
print(a)
b = np.zeros((3,3))
b[1,1]=9
print(b)
a[1:-1,1:-1]=b
print(a)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Statistics


In [90]:
stats = np.array([[1,2,3],[4,5,6]])
np.sum(stats,axis = 0 )
print(stats.nbytes)

48


In [93]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [94]:
np.full(10,9)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [96]:
np.sqrt(np.full(10,16))

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])